### PR TITLE
fix "KeyError: 'ptime'"

### LINKED ISSUE #21: Stats don't load after 2.0 Update
I was able to "successfully" install the 2.0 update, however, the plugin never loads.  I tried to uninstall the plugin and reinstall it, but that did not make any change.

### PR DESCRIPTION
**Pull request by schumar**
This should fix #21 and #30, maybe others

### CODE REVIEW

**Comment by purist69** [comment]
can you please explain how to implement?

**Comment by purist69** [comment]
I figured it out.  Implementing this change broke my Octoprint install.  replacing the file with the original got my Octoprint working again and my stats started working as well.

**Comment by joachimklug** [comment]
Tested the change. Works perfectly.

**Comment by gmccauley** [comment]
Seems to have worked for me too

**Comment by ngroulx** [comment]
I'm experiencing the issue found in bug #30 . How do I go about implementing the fix listed here?

**Comment by joachimklug** [comment]
@ngroulx check the "Files changed" tab at the very top. There you will find that the file __init__.py was changed (4 rows added, one deleted) 
So either you download that changed file or you replicate the changes in your local copy. (I mean there are other possibilities but these are the most simple/quick ones)

**Comment by schumar** [comment]
Thanks @joachimklug for explaining this!
@ngroulx , do not to include the `+` signs! So remove the line
```python
            event_df['ptime'] = event_df['ptime'].apply(self.formatNum)
```
and instead add
```python
            if 'ptime' in event_df:
                event_df['ptime'] = event_df['ptime'].apply(self.formatNum)
            else:
                event_df['ptime'] = 0
```
(make sure that those lines have 12/16 spaces at the beginning)

**Comment by schumar** [comment]
@amsbr , could you please merge this? Looks like this affects a lot of users.

**Comment by ngroulx** [comment]
> @ngroulx check the "Files changed" tab at the very top. There you will find that the file **init**.py was changed (4 rows added, one deleted)
> So either you download that changed file or you replicate the changes in your local copy. (I mean there are other possibilities but these are the most simple/quick ones)

Thanks @joachimklug and @schumar but I noticed the change was committed to the "schumar:master" branch, and doesn't yet appear to be committed to the main branch. So I went ahead and installed using the schumar branch and it works now.

**Comment by schumar** [comment]
@ngroulx : Thanks for your trust, but please make sure to switch back to `amsbr:master` when @amsbr has merged this PR; I don't plan to keep my fork up-to-date!

**Comment by SoLongSidekick** [comment]
Anyone mind spending a few minutes fully explaining how to implement this? Can it be done via SSH or does it make more sense to just pull the SD card out of my Pi and throw it in my PC to change the file? Where is the file init.py located in the file system?

**Comment by schumar** [comment]
@SoLongSidekick 
I'm assuming you are using OctoPi? Are you comfortable using an editor like `nano` or `vim`? If so,
`ssh pi@mypi` (where `mypi` is the hostname of your Pi), and then edit `oprint/lib/python2.7/site-packages/octoprint_stats/__init__.py`

Otherwise, sure, pull out the card and do it on your (Linux) PC.

**Comment by SoLongSidekick** [comment]
Yes I'm running Octopi. I have a windows PC. Is there any reason I couldn't do it with that? I'm picturing pulling the SD card, plugging it into my PC, finding the file, then using Notepad++ to edit it as necessary.

**Comment by schumar** [comment]
> I have a windows PC. Is there any reason I couldn't do it with that?

The file-system on the SD-card is ext4, which Windows can't handle.

You could try to put e.g. [Ubuntu](https://ubuntu.com/download/desktop) on a USB-stick and boot from that.

If you are neither comfortable with that, nor with the `ssh` method, you can only disable the OctoPrint-Stats for now, and wait for @amsbr to merge my fix, sorry -- this here is an issue-tracker, not a support forum :)

**Comment by SoLongSidekick** [comment]
I'm comfortable SSHing into it, I use Putty and am somewhat capable but have never used a text editor inside it. Would it be possible to cd into the right directory and swap it that way?

**Comment by SoLongSidekick** [comment]
Well I thought I had it figured out using nano, but after replacing line 395 with the lines listed above (with confirmed correct spacing before each line) now Statistics doesn't even show up as an installed plugin.

**Review by amsbr — APPROVED** [review]
Thanks for fix ptime key check

**Pull request merged**
